// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0CUp2p_qHg0LpeV1fXWEJPITBALZGsE',
    appId: '1:10413951349:web:98c9044cd8c232298a6b3c',
    messagingSenderId: '10413951349',
    projectId: 'chat-app-4f142',
    authDomain: 'chat-app-4f142.firebaseapp.com',
    storageBucket: 'chat-app-4f142.appspot.com',
    measurementId: 'G-6YRSTSREVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdqCEv9_aZkFZsenUg-a9SDT7c8Y2pP_k',
    appId: '1:10413951349:android:6af721a172a0ffca8a6b3c',
    messagingSenderId: '10413951349',
    projectId: 'chat-app-4f142',
    storageBucket: 'chat-app-4f142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkcTa87aeUUqIbC_xpxbJBv86R1H4t4I0',
    appId: '1:10413951349:ios:b7c8bc539aea289f8a6b3c',
    messagingSenderId: '10413951349',
    projectId: 'chat-app-4f142',
    storageBucket: 'chat-app-4f142.appspot.com',
    iosClientId:
        '10413951349-l8dpn450jmnflfbg1red4u7rk9s72m7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkcTa87aeUUqIbC_xpxbJBv86R1H4t4I0',
    appId: '1:10413951349:ios:b7c8bc539aea289f8a6b3c',
    messagingSenderId: '10413951349',
    projectId: 'chat-app-4f142',
    storageBucket: 'chat-app-4f142.appspot.com',
    iosClientId:
        '10413951349-l8dpn450jmnflfbg1red4u7rk9s72m7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
